INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (1, 1);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (1, 2);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (1, 3);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (1, 4);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (2, 2);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (2, 4);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (3, 3);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (3, 6);
INSERT INTO jiaoji.fllow (user_id, topic_id) VALUES (3, 9);
